# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Semmetric_difference(object):
    def setupUi(self, Semmetric_difference):
        Semmetric_difference.setObjectName("Semmetric_difference")
        Semmetric_difference.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(Semmetric_difference)
        self.centralwidget.setObjectName("centralwidget")
        self.FArrayLabel = QtWidgets.QLabel(self.centralwidget)
        self.FArrayLabel.setGeometry(QtCore.QRect(30, 50, 171, 41))
        font = QtGui.QFont()
        font.setFamily("Acumin Variable Concept Wide")
        font.setPointSize(14)
        self.FArrayLabel.setFont(font)
        self.FArrayLabel.setObjectName("FArrayLabel")
        self.SArrayLabel = QtWidgets.QLabel(self.centralwidget)
        self.SArrayLabel.setGeometry(QtCore.QRect(30, 100, 201, 41))
        font = QtGui.QFont()
        font.setFamily("Acumin Variable Concept Wide")
        font.setPointSize(14)
        self.SArrayLabel.setFont(font)
        self.SArrayLabel.setObjectName("SArrayLabel")
        self.Set_difference_f_s = QtWidgets.QPushButton(self.centralwidget)
        self.Set_difference_f_s.setGeometry(QtCore.QRect(20, 320, 91, 81))
        self.Set_difference_f_s.setObjectName("Set_difference_f_s")
        self.Symmetric_difference = QtWidgets.QPushButton(self.centralwidget)
        self.Symmetric_difference.setGeometry(QtCore.QRect(20, 480, 91, 81))
        self.Symmetric_difference.setObjectName("Symmetric_difference")
        self.Union = QtWidgets.QPushButton(self.centralwidget)
        self.Union.setGeometry(QtCore.QRect(20, 160, 91, 81))
        self.Union.setObjectName("Union")
        self.Intersection = QtWidgets.QPushButton(self.centralwidget)
        self.Intersection.setGeometry(QtCore.QRect(20, 240, 91, 81))
        self.Intersection.setObjectName("Intersection")
        self.SArrayEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.SArrayEdit.setGeometry(QtCore.QRect(250, 100, 461, 31))
        self.SArrayEdit.setObjectName("SArrayEdit")
        self.FArrayEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.FArrayEdit.setGeometry(QtCore.QRect(250, 50, 461, 31))
        self.FArrayEdit.setObjectName("FArrayEdit")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(160, 300, 111, 61))
        font = QtGui.QFont()
        font.setFamily("MS Mincho")
        font.setPointSize(24)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.output = QtWidgets.QLabel(self.centralwidget)
        self.output.setGeometry(QtCore.QRect(280, 300, 401, 61))
        font = QtGui.QFont()
        font.setFamily("Minion Variable Concept Semibol")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.output.setFont(font)
        self.output.setText("")
        self.output.setObjectName("output")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(230, 40, 71, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_3.setFont(font)
        self.label_3.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(230, 90, 71, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_4.setFont(font)
        self.label_4.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(720, 90, 71, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_5.setFont(font)
        self.label_5.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(720, 40, 71, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_6.setFont(font)
        self.label_6.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_6.setObjectName("label_6")
        self.Set_difference_s_f = QtWidgets.QPushButton(self.centralwidget)
        self.Set_difference_s_f.setGeometry(QtCore.QRect(20, 400, 91, 81))
        self.Set_difference_s_f.setObjectName("Set_difference_s_f")
        Semmetric_difference.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(Semmetric_difference)
        self.statusbar.setObjectName("statusbar")
        Semmetric_difference.setStatusBar(self.statusbar)

        self.retranslateUi(Semmetric_difference)
        QtCore.QMetaObject.connectSlotsByName(Semmetric_difference)

    def retranslateUi(self, Semmetric_difference):
        _translate = QtCore.QCoreApplication.translate
        Semmetric_difference.setWindowTitle(_translate("Semmetric_difference", "MainWindow"))
        self.FArrayLabel.setText(_translate("Semmetric_difference", "Enter first set A:"))
        self.SArrayLabel.setText(_translate("Semmetric_difference", "Enter second set B :"))
        self.Set_difference_f_s.setText(_translate("Semmetric_difference", "Set difference \n"
"  A  \\  B"))
        self.Symmetric_difference.setText(_translate("Semmetric_difference", "Symmetric \n"
" difference"))
        self.Union.setText(_translate("Semmetric_difference", "Union"))
        self.Intersection.setText(_translate("Semmetric_difference", "Intersection "))
        self.label.setText(_translate("Semmetric_difference", "Answer:"))
        self.label_3.setText(_translate("Semmetric_difference", "{"))
        self.label_4.setText(_translate("Semmetric_difference", "{"))
        self.label_5.setText(_translate("Semmetric_difference", "}"))
        self.label_6.setText(_translate("Semmetric_difference", "}"))
        self.Set_difference_s_f.setText(_translate("Semmetric_difference", "Set difference  \n"
" B  \\  A"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Semmetric_difference = QtWidgets.QMainWindow()
    ui = Ui_Semmetric_difference()
    ui.setupUi(Semmetric_difference)
    Semmetric_difference.show()
    sys.exit(app.exec_())
